services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12900921
      MYSQL_DATABASE: "mysql-1"
      MYSQL_USER: "user-mysql-1"
      MYSQL_PASSWORD: 12900921
      MYSQL_TCP_PORT: "3306"
    ports:
      - "3306:3306"

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "1111:1111"
    environment:
      - PORT=1111
    volumes:
      - ./user-service/src:/app/src
    depends_on:
      - db

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "2222:2222"
    volumes:
      - ./notification-service/src:/app/src
    depends_on:
      - user-service
