services:
  db:
    container_name: mysql-container
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12900921
      MYSQL_DATABASE: "mysql-1"
      MYSQL_USER: "user-mysql-1"
      MYSQL_PASSWORD: 12900921
      MYSQL_TCP_PORT: "3306"
    ports:
      - "3306:3306"
  redis:
    container_name: redis-container
    image: redis:latest
    ports:
      - "6379:6379"
  notification-service:
    container_name: notification-service-container
    build:
      context: ./notification-service
      dockerfile: Dockerfile
      args:
        WEBHOOK_URL: ${WEBHOOK_URL}
    ports:
      - "2222:2222"
    volumes:
      - ./notification-service/src:/app/src
    depends_on:
      - redis
      - db
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
  user-service:
    container_name: user-service-container
    build:
      context: ./user-service
      dockerfile: Dockerfile
      args:
        - NOTIFICATION_DELAY=${NOTIFICATION_DELAY}
    ports:
      - "1111:1111"
    environment:
      - NOTIFICATION_DELAY=${NOTIFICATION_DELAY}
    volumes:
      - ./user-service/src:/app/src
    depends_on:
      - redis
      - db
